name: wedy
description: "Wedy - organize your wedding!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  jwt_decoder: ^2.0.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  go_router: ^15.2.4
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.5.3
  icons_flutter: ^0.0.5
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  build_runner: ^2.5.4

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
    
    - family: SFProHeavy
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf     
